version: '2'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./dev/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./dev/etc/nginx/inc:/etc/nginx/inc
      - ./dev/etc/nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80

  mariadb:
    image: mariadb:10.5
    command: --max_allowed_packet=32505856
    environment:
      MARIADB_ROOT_PASSWORD: Root12+#
      MARIADB_USER: starterUser
      MARIADB_PASSWORD: Demo12+#
      MARIADB_DATABASE: starterProject
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./backup/mariadb.sql:/docker-entrypoint-initdb.d/mariadb.sql
      - mariadb:/bitnami/mariadb
      - mariadb-boot:/opt/bitnami/mariadb/.bootstrap
    ports:
      - 3306:3306

  tomcat:
    image: tomcat:9
    volumes:
      - ./target/StarterProject-1.0-SNAPSHOT:/usr/local/tomcat/webapps/backend
    ports:
      - 8080:8080
    environment:
      - MYSQL_PASSWORD=Demo12+#
      - MYSQL_URL=jdbc:mysql://mariadb:3306/starterProject
      - MYSQL_USER=starterUser

  angular:
    image: cloudstart-angular-frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 4200:4200

volumes:
  mariadb:
    driver: local
  mariadb-boot:
    driver: local

